#!/usr/bin/env zsh --no-rcs
# vim:set noet sts=0 sw=4 ts=4 tw=79 fdm=marker:

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `bootstrap` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# ~/.gitconfig has insteadOf configs that changes https to git. This won't work
# unless we already have the .ssh decrypted. Moving it out and in is the safest
# option
if [ ! -f ~/.ssh/id_rsa ]; then
	echo "ssh identify not found, checking url.git* configs"
	URL_GITHUB="$(git config --global --get url.git@github.com:.insteadof)"
	if [ -n ${URL_GITHUB} ]; then
		trap "git config --global url.git@github.com:.insteadof ${URL_GITHUB}" EXIT INT TERM
		git config --global --unset url.git@github.com:.insteadof
	fi
fi

cd "$HOME"


export YADM_BOOTSTRAPPING=yes

echo "\nInit submodules\n"
yadm submodule update --recursive --init

OS=$(uname -s) # Linux or Darwin

if [ -f "$HOME/.Brewfile" ]; then
	echo "\nUpdating homebrew bundle\n"
	brew bundle --global
fi

[ -z "${HOMEBREW_PREFIX}" ] && eval "$(brew shellenv)"

if [ ! -d $HOME/.config/base16-shell ]; then
	echo "\nInstalling base16 shell\n"
	git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
fi

# }}}

if [ "${OS}" = "Darwin" ]; then
	echo "\nSetting MacOS defaults\n"
	bash $HOME/.config/yadm/macos
fi

echo "\n# Now clone encrypt notes:"
echo
echo "gpg --import gpg-priv-jackie-space.key"
echo
echo "The private key should be stored safely in a external USB."
echo
echo "yadm decrypt # this requirees the gpg key to be imported"

if [[ -f ~/.gitconfig && -d ~/.ssh/id_rsa ]] ; then
	echo "\nUpdating the yadm repo origin URL\n"
	yadm remote set-url origin "git@github.com:jackielii/dotfiles.git"
else
	echo "\n# After restore ssh keys, do:"
	echo "yadm remote set-url origin git@github.com:jackielii/dotfiles.git"
fi

echo
echo "git clone gcrypt::git@github.com:jackielii/notes.git"
echo "cd notes"
echo "git checkout main"
echo
echo "# restart these after giving permissions"
echo "brew services restart yabai"
echo "brew services restart skhd"
echo
echo "# Also checkout yabai wiki to disable SIP"
echo "# https://github.com/koekeishiya/yabai/wiki/"

echo Check list
echo - zigup default 0.14.0
echo - rustup default stable
echo - nvm via nvim.sh or brew install nvm
