#!/usr/bin/env zsh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          true
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child

# floating windows are always on top (default: off)
# yabai -m config window_topmost               off

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow                float

yabai -m config active_window_opacity        1
# yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off

# # border
# yabai -m config window_border_width 10
# yabai -m config active_window_border_color 0xffffffff
# yabai -m config normal_window_border_color 0xff555555
# yabai -m config window_border off

# Mouse support
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               9
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   8

# pinned apps to space
yabai -m rule --add app='^Microsoft Teams$' space=3
yabai -m rule --add app='^MSTeams$' space=3

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add title='Preferences$' manage=off
# yabai -m rule --add app='^Finder$' manage=off
yabai -m rule --add app='^AltTab$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app='^Mac Mouse Fix$' manage=off
yabai -m rule --add app='^Maccy$' manage=off
yabai -m rule --add app='^Happy Hacking Keyboard Keymap Tool$' manage=off
yabai -m rule --add app='^GIMP-' manage=off
# yabai -m rule --add app='^VLC$' manage=off
# yabai -m rule --add app='^WeChat$' manage=off
yabai -m rule --add app='^Webex$' manage=off
yabai -m rule --add app='^Steam.*$' manage=off
yabai -m rule --add app='Dota 2' manage=off
yabai -m rule --add title='^MY-|-Filer$' manage=off grid=8:8:1:1:6:6
yabai -m rule --add app='^Calculator$' manage=off

# scratchpad windows
yabai -m rule --add app="^YT Music$" scratchpad=music grid=11:11:1:1:9:9
yabai -m rule --add title="^T_T$" scratchpad=tt grid=11:11:1:1:9:9
yabai -m rule --add app="^WeChat$" scratchpad=wechat grid=11:11:1:1:9:9
yabai -m rule --add app='WhatsApp$' scratchpad=whatsapp grid=11:11:1:1:9:9
yabai -m rule --add app="^Finder$" scratchpad=finder grid=11:11:1:1:9:9
yabai -m rule --add app="^Notes$" scratchpad=notes grid=11:11:1:1:9:9
yabai -m rule --add app="^ChatGPT$" scratchpad=chatgpt grid=11:11:1:1:9:9
yabai -m rule --add app="^Skype$" scratchpad=skype grid=11:11:1:1:9:9

#SPACEBAR_HEIGHT=$(spacebar -m config height)
#yabai -m config external_bar all:${SPACEBAR_HEIGHT}:0

# yabai-indicator
yabai -m signal --add event=mission_control_exit action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_added action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=display_removed action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_created action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_destroyed action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_focused action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_moved action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_resized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_minimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
yabai -m signal --add event=window_deminimized action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'

echo "yabai configuration loaded.."
