return {
  { import = "lazyvim.plugins.extras.linting.eslint" },
  { import = "lazyvim.plugins.extras.formatting.prettier" },
  { import = "lazyvim.plugins.extras.lang.json" },
  { import = "lazyvim.plugins.extras.lang.typescript" },
  { import = "lazyvim.plugins.extras.lang.tailwind" },
  { import = "lazyvim.plugins.extras.lang.java" },
  -- { import = "lazyvim.plugins.extras.lang.markdown" },
  -- { import = "lazyvim.plugins.extras.coding.blink" },

  { import = "lsp.extras.lang.python" },
  { import = "lsp.extras.lang.go" },
  { import = "lsp.extras.lang.zig" },
  { import = "lsp.extras.lang.sql" },
  { import = "lsp.extras.lang.htmx_html_templ" },
  { import = "lsp.extras.lang.tex" },
  -- { import = "lsp.extras.lang.tailwind" },
  { import = "lsp.extras.lang.clangd" },
  { import = "lsp.extras.lang.proto" },
  { import = "lsp.extras.lang.lua" },
  { import = "lsp.extras.lang.xml" },
}
